#FROM resin/rpi-raspbian:buster
#FROM balenalib/raspberrypi3:buster
FROM opencv
#FROM balenalib/raspberrypi4-64-debian:latest-build-20191122

# for TZ data
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing
RUN apt-get install -y git

# Recommended installation options for ubuntu 18.04
RUN apt install -y pkg-config git cmake build-essential nasm wget python3-setuptools libusb-1.0-0-dev  python3-dev python3-pip python3-numpy python3-scipy libglew-dev libglfw3-dev libtbb-dev
RUN apt install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev ffmpeg x264 x265 libportaudio2 portaudio19-dev
#RUN apt install -y python3-opencv libopencv-dev
RUN apt install -y libgoogle-glog-dev libatlas-base-dev libeigen3-dev
RUN apt install -y libceres-dev


RUN mkdir -p /home/user
WORKDIR /home/user

# install Turbojet
RUN wget -O libjpeg-turbo.tar.gz https://sourceforge.net/projects/libjpeg-turbo/files/1.5.1/libjpeg-turbo-1.5.1.tar.gz/download && \
    tar xvzf libjpeg-turbo.tar.gz && \
    cd libjpeg-turbo-1.5.1 && \
    ./configure --enable-static=no --prefix=/usr/local && \
    make install -j4 && \
    ldconfig

#RUN apt-get install -y libuvc-dev

RUN git clone https://github.com/pupil-labs/libuvc && \
    cd libuvc && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && make install

# enable libuvc as normal user
#RUN echo 'SUBSYSTEM=="usb",  ENV{DEVTYPE}=="usb_device", GROUP="plugdev", MODE="0664"' | tee /etc/udev/rules.d/10-libuvc.rules > /dev/null && \
#    udevadm trigger

RUN apt-get install -y python3-venv

SHELL ["/bin/bash", "-c"]

RUN cd /home/user
RUN python3 -m venv venv

# python 3.6
#RUN apt-get install build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev
#RUN cd && wget https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tgz && \
#	tar xf Python-3.6.7.tgz && \
#	cd Python-3.6.7 && \
#	./configure && \
#	make && \
#	make altinstall

#RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
#RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.6 2
#RUN sudo update-alternatives --config python
#RUN update-alternatives  --set python3 /usr/local/bin/python3.6


#install python libraries
RUN pip3 -v install cysignals
RUN pip3 install cython
RUN pip3 install msgpack==0.5.6
RUN pip3 install numexpr
RUN pip3 install packaging
RUN pip3 install psutil
RUN pip3 install pyaudio
RUN pip3 install pyopengl
RUN pip3 install pyzmq
RUN pip3 install scipy
RUN pip3 install git+https://github.com/zeromq/pyre
RUN pip3 install scikit-build
RUN pip3 install git+https://github.com/pupil-labs/PyAV
RUN pip3 install git+https://github.com/pupil-labs/pyuvc
RUN pip3 install git+https://github.com/pupil-labs/pyndsi
RUN pip3 install git+https://github.com/pupil-labs/pyglui
#RUN pip3 install git+https://github.com/pupil-labs/nslr
#RUN pip3 install git+https://github.com/pupil-labs/nslr-hmm


RUN pip3 install pyyaml

RUN pip3 install six Pillow

RUN pip3 install numpy

RUN git clone https://github.com/JojoDevel/nslr.git && cd nslr && pip3 install .

RUN pip3 install git+https://github.com/pupil-labs/nslr-hmm

#RUN pip3 install pupil_apriltags
RUN git clone --recurse-submodules https://github.com/JojoDevel/apriltags #this is for docker

RUN cd apriltags && pip3 install -e .[dev]

RUN apt-get install mesa-utils

# Configure Kodi group
RUN usermod -a -G audio root && \
usermod -a -G video root && \
usermod -a -G dialout root && \
usermod -a -G plugdev root && \
usermod -a -G tty root

#RUN git clone https://github.com/JojoDevel/pupil.git
